[theme]
base="dark"
primaryColor="#636efa"
backgroundColor="#202239"
secondaryBackgroundColor="#35374c"

[server]
headless = false
enableCORS = true

[client]
toolbarMode = "minimal"  # This hides the settings menu


