[theme]
base="dark"
primaryColor="#83c9ff"
backgroundColor="#202239"
secondaryBackgroundColor="#35374c"

[server]
port = 8000
headless = true
enableCORS = false
address = "0.0.0.0"

[client]
toolbarMode = "minimal"  # This hides the settings menu


